### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by ghost** [gaffner/PyBitTorrent#20]
Why is the file not being downloaded from the torrent file? Windows 10

**Comment by gaffner** [comment]
> Why is the file not being downloaded from the torrent file? Windows 10

Hi!  what do you mean? does the script don't work for you? can  you attach the output? Thanks  :)

**Comment by ghost** [comment]
The script is the same as yours on readme.md .
Code:
from PyBitTorrent import TorrentClient

client = TorrentClient('1.torrent')
client.start()

**Comment by gaffner** [comment]
And the file is not being downloaded? What is the output? Have you tried to
use the example script?

**Comment by gaffner** [comment]
I guess you got along ;)
