### ISSUE TITLE
Peer scraping limtied to 200?

### ISSUE THREAD

**Issue by AusAgentSmith** [gaffner/PyBitTorrent#21]
I have dug through the code and cannot work out why there is a 200 limit on peer returns?

2024-01-06 22:52:39.226 INFO UDPTracker - get_peers: success in scraping ***** got 200 peers?

**Comment by AusAgentSmith** [comment]
*is this trackers limiting their return to 200?

**Comment by gaffner** [comment]
Hi! can you attach the full output\scriptshot? if you can give me the torrent file itself it can be great to.
There should be no such restriction, and im not familiar with any global limition in  the number of peers.  it can be implemented in the UDP Tracker side however.
Again, send me more info and  i'll be happy to help you :)

**Comment by AusAgentSmith** [comment]
Hey Gaffner,

I did some quick googling lastnight and there is suggestion that most trackers will only respond with the top/most appropriate peers limited to 200. Kind of a bummer given the project i'm working on (which isnt to actually download the content!).

Am now wondering if DHT, PEX or LsD may yeild more peers..

**Comment by gaffner** [comment]
Sorry to hear that! Maybe DHT will answer your needs. Anyway thank you for using my python library!

This research you do, is it part of your work or just for fun? Im curious.

**Comment by AusAgentSmith** [comment]
Fun. Nothing to do with work thankfully!
