### ISSUE TITLE
raise Exception("No peers found") Exception: No peers found

### ISSUE THREAD

**Issue by ghost** [gaffner/PyBitTorrent#24]
C:\Users\Ирбис>python 52.py
{
    'comment': 'иконку можно самому скачать или сделать свою
https://raw.githubusercontent.com/LeonardNekit/WinArhive/main/logo.ico',
    'created by': 'qBittorrent v4.6.3',
    'creation date': 1711363044,
    'info': {
        'file tree': {
            'logo.ico': {
                '': {
                    'length': 55262,
                    'pieces root':
b'\xb4(\xbb\xb7`\x88\x9eC\x97\x9c\xe0@W\xbdGw\x14d\x13\x8d\xd8\x9e\x03]R\x04L\xbb\xb6\xfc\xb6\xd6'
                }
            }
        },
        'length': 55262,
        'meta version': 2,
        'name': 'logo.ico',
        'piece length': 16384,
        'pieces': '',
        'source': 'https://leonardnekit.github.io/WinArhive/main.html'
    },
    'piece layers': {
        b'\xb4(\xbb\xb7`\x88\x9eC\x97\x9c\xe0@W\xbdGw\x14d\x13\x8d\xd8\x9e\x03]R\x04L\xbb\xb6\xfc\xb6\xd6':
b'\xe0\x9eo\x80,\x02Ger\x16\xa6x#\x9b\x1b\xae\x98<\xa2\xd2owEQ\xc0\xd7\x1b*\xdaw\x07M5"(\x9b\xa6\x00\x98_\xb5P\xda\xf5\
xf7\xf3\x97\x04\xaa\xe3\xb5\x8f1\xf0\xf5\xf3\xed\xd5T\x07\xac^[\xba\xb5\x85A!/\xcfn\xf6\xf3\x0f\xeb[\x8a\xb9\xdb\xf5\xd
6\xb81\xf1Z\x98\xa6x\xcf\xec\xfb\x91{\xee\x9b\x0e\xb8!\x94G[4a88M&\xd2\xbe\xb1\x83\x9f\xeaJ\xbdtpC\x98\x93\x88\xcf\xfc\
xf7\xe7\xbdoV'
    }
}
Traceback (most recent call last):
  File "C:\Users\Ирбис\52.py", line 4, in <module>
    client.start()
  File "C:\Users\Ирбис\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyBitTorrent\Bittorrent.py", line 98, in start
    raise Exception("No peers found")
Exception: No peers found

```py
from PyBitTorrent import TorrentClient

client = TorrentClient('logo.ico.torrent')
client.start()
```

**Comment by gaffner** [comment]
> C:\Users\Ирбис>python 52.py
> {
>     'comment': 'иконку можно самому скачать или сделать свою
> https://raw.githubusercontent.com/LeonardNekit/WinArhive/main/logo.ico',
>     'created by': 'qBittorrent v4.6.3',
>     'creation date': 1711363044,
>     'info': {
>         'file tree': {
>             'logo.ico': {
>                 '': {
>                     'length': 55262,
>                     'pieces root':
> b'\xb4(\xbb\xb7`\x88\x9eC\x97\x9c\xe0@W\xbdGw\x14d\x13\x8d\xd8\x9e\x03]R\x04L\xbb\xb6\xfc\xb6\xd6'
>                 }
>             }
>         },
>         'length': 55262,
>         'meta version': 2,
>         'name': 'logo.ico',
>         'piece length': 16384,
>         'pieces': '',
>         'source': 'https://leonardnekit.github.io/WinArhive/main.html'
>     },
>     'piece layers': {
>         b'\xb4(\xbb\xb7`\x88\x9eC\x97\x9c\xe0@W\xbdGw\x14d\x13\x8d\xd8\x9e\x03]R\x04L\xbb\xb6\xfc\xb6\xd6':
> b'\xe0\x9eo\x80,\x02Ger\x16\xa6x#\x9b\x1b\xae\x98<\xa2\xd2owEQ\xc0\xd7\x1b*\xdaw\x07M5"(\x9b\xa6\x00\x98_\xb5P\xda\xf5\
> xf7\xf3\x97\x04\xaa\xe3\xb5\x8f1\xf0\xf5\xf3\xed\xd5T\x07\xac^[\xba\xb5\x85A!/\xcfn\xf6\xf3\x0f\xeb[\x8a\xb9\xdb\xf5\xd
> 6\xb81\xf1Z\x98\xa6x\xcf\xec\xfb\x91{\xee\x9b\x0e\xb8!\x94G[4a88M&\xd2\xbe\xb1\x83\x9f\xeaJ\xbdtpC\x98\x93\x88\xcf\xfc\
> xf7\xe7\xbdoV'
>     }
> }
> Traceback (most recent call last):
>   File "C:\Users\Ирбис\52.py", line 4, in <module>
>     client.start()
>   File "C:\Users\Ирбис\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyBitTorrent\Bittorrent.py", line 98, in start
>     raise Exception("No peers found")
> Exception: No peers found
> 
> ```py
> from PyBitTorrent import TorrentClient
> 
> client = TorrentClient('logo.ico.torrent')
> client.start()
> ```

HI! It looks like you don't have any peers. It means 0 peers returned from the tracker... You can try downloading it using other torrent clients like BitTorrent and see if that works. If yes, it retrieves it using DHT which is not supported in this program. But you can write those peers into a text file and feed the program with it.
If not, it is simply a very old torrent.

Thank you for using PyBitTorrent
