### ISSUE TITLE
Failing to download any torrent

### ISSUE THREAD

**Issue by wLxCvcY20V** [gaffner/PyBitTorrent#25]
I wanted to reproduce the [BitTorrent over Tor de-anonymization](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea/) issues, but I'm unable to download any torrents. First I tried through Tor, then I tried other proxies, then I used my public address. All of them failed. Do you have any idea of what could it be the cause? I'm setting `max_peers` to 1 to avoid harming the Tor network.

I also made some modifications to the code like setting timeout, getting peers from the command line instead of a file, and split the start method of the TorrentClient object into start and setup to get info without actually starting downloading. Are you interested in these modifications?

**Comment by gaffner** [comment]
Hi! can you attach the output from the script?
the reasonable reason i can think about is that this **torrent have no peers**, at least not from traditional way (using Trackers server). it might relay on DHT only, and this type of method have no support in PyBitTorrent (maybe you can add support ;) ).
Anyway, that's one possible, and easy to check - just try to download it using torrent client that worked for you, and look for its output where it got the peers from - DHT or Tracker, and if there is no such output - you can sniff. Another way is to interact with the Tracker Directly, in HTTP or UDP, and by that refute this theory.

But if you give the peers in command line, then it is weird. What was the failure reason? is there a trackback? any information can help (you can even give me torrent for example that didnt worked for you and ill try debug myself)

About the changes - if they are optional and give added value to the user, then it could be great, submit PR :)

**Comment by wLxCvcY20V** [comment]
I used the latest Linux Mint ISO torrent. There was no failure nor traceback. The tracker sent plenty of peers, and DHT don't seem to be the problem here. I tested with webtorrent-cli setting the DHT port to 10005 and dropping any incoming and outgoing connections to this port with iptables and the torrent downloaded normally.

But I think I figured the problem. Apparently the peer that I was connecting to was not sending any data and even if there are other peers, the program will not try to connect to them. I will create a conditional that disconnects from the peer if it doesn't send any data after a timeout and connects to another available peer.

I will wait for you to review my PR before changing more things in to code. But I do intent to work more on it, it seems promising.

**Comment by gaffner** [comment]
That's sound wonderful!
so after this fix, does PyBitTorrent managed to download Linux Mint?
It's weird this peer is always the first peer, although it can happen sometimes in this type of torrents (for example, many times you download ISO torrent from InternetArchive you always have the 1 same peer)

**Comment by wLxCvcY20V** [comment]
Yes it downloaded. I also got a better understanding of the leak the I was trying to reproduce. It happens that the tracker sends the IP from the receiver and the port specified in the data sent, therefore it uses the exit node IP address, and because only the tracker has a circuit with your computer, it makes all the peers attempt to connect to the exit node instead of your computer who actually has the port open. And because of this behavior some BitTorrent clients purposefully send your real IP address in the data so the peers know the computer they should connect to. This means that PyBitTorrent doesn't leak, which is good.

To make BitTorrent work over Tor the trackers would have to send an instruction to the peers to create a circuit to your computer and that's where the overloading happens.
