### ISSUE TITLE
Major changes in the code

### ISSUE THREAD

**Issue by wLxCvcY20V** [gaffner/PyBitTorrent#27]
I've been thinking in making some major changes in the code before implementing new features and fixing some issues that I found. Here are my ideas:

- Using `__new__` in factory classes to seamlessly instantiate new objects
- Attribute `peers` in tracker objects to store its peers
- Manager classes are used to work on operations involving multiple objects of the same type
- Option to use peers from both file and trackers
- Reorganizing the code (like putting all tracker types in the same file and when they grow bigger create a folder for splitting them in other files)

Issues that I found:

- Some trackers don't send the peer ID (debian tracker in this case)
- `info_hash` attribute not being initialized (not sure why)

Note that I'm not much familiar with dealing with binary files and raw protocol responses. But I will give it a read to continue expanding the project.

Let me know what you think.

**Comment by gaffner** [comment]
That's sound awesome!
If you can make this changes and fixing the issues you found, it will be great.
The current structure of the project it is bit "messy" - it should be organized in folders for each class,
even if this folder will contain only one file.
Your changes sounds very useful - go for it.

I made you collaborator to this project, so you can now commit directly to the project (its better to do them in new branch,in this format: feature/XXX-XXX-XX, and then make merge request to ```main``` and put me as reviewer).

@Sprooty if you have any opinion regarding this feel free to share :)

**Comment by gaffner** [comment]
Any new? :)

**Comment by wLxCvcY20V** [comment]
@gaffner Right now I'm with some connection issues, I'll probably have to switch my current provider. Currently, I only have access to mobile network.
